const menu = [
    {
        id: 1,
        title: 'buttermilk pancakes',
        category: 'breakfast',
        price: 15.99,
        img: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/51a9c5b156c84977ae50004b5ef622b2/finalFB.jpg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
        id: 2,
        title: 'diner double',
        category: 'lunch',
        price: 13.99,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3NTatmuTOTjvUdzqwhOFiaSSTv2xBxqYtn8lPEoV46vRPPcPgnVV1fnnZWVMJ6eZ-8BE&usqp=CAU',
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
        id: 3,
        title: 'godzilla milkshake',
        category: 'shakes',
        price: 6.99,
        img: 'https://media.istockphoto.com/photos/milk-shakes-in-plastic-cups-and-straws-on-a-dark-wooden-table-picture-id1311373994?b=1&k=20&m=1311373994&s=170667a&w=0&h=jBCnbjNhWueI5JJNV1Qagba2ek8PtGM9iZjmcPaSJPI=',
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
        id: 4,
        title: 'country delight',
        category: 'breakfast',
        price: 20.99,
        img: 'https://www.fmnfoods.com/wp-content/uploads/2021/03/EGUSI-WITH-BALL-8-1-scaled.jpg',
        desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
        id: 5,
        title: 'egg attack',
        category: 'lunch',
        price: 22.99,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVT6z7IVWsieuaFbn9O8W1_Se8rioeb8HdcA&usqp=CAU',
        desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
        id: 6,
        title: 'oreo dream',
        category: 'shakes',
        price: 18.99,
        img: 'https://i.pinimg.com/originals/85/ec/a7/85eca742fc516a74e0f7187a43763b85.jpg',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 7,
        title: 'bacon overflow',
        category: 'breakfast',
        price: 8.99,
        img: 'https://natashaskitchen.com/wp-content/uploads/2021/03/Air-Fryer-Bacon-4-500x500.jpg',
        desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
        id: 8,
        title: 'american classic',
        category: 'lunch',
        price: 12.99,
        img: 'https://worldoffoodanddrink.worldtravelguide.net/wp-content/uploads/2018/07/shu-American-food-421470679-Brent-Hofacker-1440x823.jpg',
        desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
        id: 9,
        title: 'quarantine buddy',
        category: 'shakes',
        price: 16.99,
        img: 'https://c.ndtvimg.com/2020-03/2938buvo_taco-roti_625x300_27_March_20.jpg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
];
export default menu;